# config/packages/monolog.yaml
monolog:
    handlers:
        # Handler padrão de arquivo para logs
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug

        # Handler de e-mail para erros críticos
        mailer:
            type: service
            id: monolog.handler.mailer
            level: error
            channels: ['!event']
        
        # Handler de e-mail para exceções
        mailer_exception:
            type: service
            id: monolog.handler.mailer_exception
            level: critical
            channels: ['!event']

services:
    # Serviço para o handler de e-mail
    monolog.handler.mailer:
        class: Symfony\Bridge\Monolog\Handler\SwiftMailerHandler
        arguments:
            - '@mailer'
            - 'error@example.com'
            - 'Log Error'
            - ['error']

    # Serviço para o handler de e-mail para exceções
    monolog.handler.mailer_exception:
        class: Symfony\Bridge\Monolog\Handler\SwiftMailerHandler
        arguments:
            - '@mailer'
            - 'exception@example.com'
            - 'Critical Error'
            - ['critical']
