# config/packages/monolog.yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        email:
            type: fingers_crossed
            action_level: error
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'gustavolarsen10@gmail.com'
            to_email: 'gustavo.larsen@zport.com.br'
            subject: 'An Error Occurred!'
            level: debug
            formatter: monolog.formatter.html