CREATE TABLE usuario (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    tipo BIGINT,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tipo) REFERENCES tipo_usuario(id)
);

DELIMITER //

CREATE TRIGGER set_default_tipo BEFORE INSERT ON usuario
FOR EACH ROW
BEGIN
    IF NEW.tipo IS NULL THEN
        SET NEW.tipo = (SELECT id FROM tipo_usuario WHERE tipo = 'CLIENTE');
    END IF;
END //

DELIMITER ;